### ISSUE TITLE
error after training at word level

### ISSUE THREAD

**Issue by kamrul29** [minimaxir/textgenrnn#104]
ValueError: Layer #1 (named "embedding"), weight <tf.Variable 'embedding/embeddings:0' shape=(465, 100) dtype=float32_ref> has shape (465, 100), but the saved weight has shape (4383, 100)

i trained a txt file with word level then tried to "
from textgenrnn import textgenrnn

textgen = textgenrnn('textgenrnn_weights.hdf5')"

then it shows this error

**Comment by minimaxir** [comment]
You must load the other files generated as well, e.g.

```
textgen_2 = textgenrnn(weights_path='new_model_weights.hdf5',
                       vocab_path='new_model_vocab.json',
                       config_path='new_model_config.json')
```
