### ISSUE TITLE
Cannot install on windows because "failed building wheel for PyYAML"

### ISSUE THREAD

**Issue by micoloth** [minimaxir/textgenrnn#11]
I'm using windows 10, i have python 3.6, 3.6 64bit and 3.5 installed.

doing `pip3 install textgenrnn` requires Pyyaml and produces error `Failed building wheel for pyyaml`.
Doing `pip3 install --ugrade Pyyaml`  or `pip install --ugrade Pyyaml` is the same.

Do you know any fix?

**Comment by birogeri** [comment]
Try downloading and installing it from here https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyyaml with `pip3 --install "C:\{file location}\PyYAML‑3.12‑{appropiate version name}.whl`

**Comment by micoloth** [comment]
That worked, thanks!
