### ISSUE TITLE
Expose a Method to Export as a SavedModel

### ISSUE THREAD

**Issue by elithrar** [minimaxir/textgenrnn#111]
e.g. https://www.tensorflow.org/api_docs/python/tf/contrib/saved_model/save_keras_model

This would be useful for training a textgenrnn network and saving the model for use elsewhere - beyond just the weights - e.g. for online prediction.

PS: Filing this issue as a heads-up - I also intend to work on this if there's no objection. I'd expose a `.export_savedmodel(filepath)` method on the textgenrnn instance to keep it simple.

**Comment by minimaxir** [comment]
The model architecture is created at runtime since it's modular (e.g. different RNNs for CPU and GPU). 

I'm not sure what the benefits are for saving the model itself instead of just the weights, the loading the weights into the model.
