### ISSUE TITLE
Can you add transformer model to it?

### ISSUE THREAD

**Issue by aletote** [minimaxir/textgenrnn#112]
I think is the state of the art in attention.

**Comment by minimaxir** [comment]
No.

Attention and Transformers are different approaches; the current attention one is fine for now. GPT-2 does use a transformer approach though.

**Comment by bjourne** [comment]
How about now? :P Transformers have proved to be superior to RNNs.

**Comment by minimaxir** [comment]
That is handled in https://github.com/minimaxir/aitextgen

textgenrnn may be depreciated once the tis in a good state
