### ISSUE TITLE
Modifying "generate_to_file" function to append, rather than write to a file

### ISSUE THREAD

**Issue by akinhwan** [minimaxir/textgenrnn#117]
I know that if I just change the 'w' to a 'a' it will work. But is there a way of doing this other than forking this repo, making my change, and then using the function that way?
Or if other find it useful I could make a PR for this slightly modified function, or make it accept as arguments 'a' or 'w'
Thank you

**Comment by Calendis** [comment]
You could always just do this on a local copy
