### ISSUE TITLE
Creating new models and issues with embedding.

### ISSUE THREAD

**Issue by doneforaiur** [minimaxir/textgenrnn#123]
train_new_model with different parameters(rnn_size = 200, rnn_layers = 4) gives following error;
```
  File "C:\ProgramData\Anaconda3\envs\tensorflow-gpu\lib\site-packages\keras\engine\saving.py", line 1149, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #2 (named "rnn_1"), weight <tf.Variable 'rnn_1/kernel:0' shape=(100, 800) dtype=float32_ref> has shape (100, 800), but the saved wei
ght has shape (100, 512).
```

Edit; Why do we care about last saved weights? 

Edit2; Forgot to reset the model. Sorry.

**Comment by ihayet** [comment]
I had also been having the same issue where that was a shape conflict between the saved weights and the weights for the new model. The following execution flow worked for me:

#----------------------------------- TRAINING FOR THE FIRST TIME -----------------------------------#

> textgen = textgenrnn()    # textgenrnn should be instantiated without any parameters
> textgen.reset()                 # important step to decouple the saved weights
> textgen.train ...

And then, we get the config, vocab and weights files that we can later reuse to instantiate a new textgenrnn object and retrain from there.

#----------------------------------- RE-TRAINING -----------------------------------#

> textgen = textgenrnn(config_path=..., vocab_path=..., weights_path=...)
> 
> textgen.train(... , new_model=True, ...)
