### ISSUE TITLE
Word-level enhancements

### ISSUE THREAD

**Issue by minimaxir** [minimaxir/textgenrnn#13]
Word level addition was a last-min change, so need to work on it a bit:

* Make sure the `vocab` abides by `max_length`.
* Add a feature to collapse punctuation.

**Comment by Dennis1989** [comment]
Are there other parameters to set (apart from word_level)? For me it just generates blank sentences on word level trained nets.

**Comment by Dennis1989** [comment]
Ok nevermind. The problem was that the character based vocabulary was build. Also an issue was that  when using textgen.train_from_file(new_model=True), the default config will be used, even if you specified the config path when generating the textgenrnn instance.

**Comment by minimaxir** [comment]
Word level should be working better in 1.1.
