### ISSUE TITLE
Colab trouble w/ training more than once?

### ISSUE THREAD

**Issue by janelleshane** [minimaxir/textgenrnn#14]
I've been trying out the collab notebook (awesome!) and think I'm seeing an issue where the training only works the first time - if I try to train again, even if I change datasets or re-upload the original dataset, it converges toward something that looks nothing like my original data.

**Comment by minimaxir** [comment]
Granted, I tried out including Colaboratory as an experiment and have found quite a few random bugs with the included VM.

There may be another implementation of maintaining the file data which is more stable (by reading from the uploaded file instead of the uploaded data).

**Comment by minimaxir** [comment]
I modified the notebook to force it to read from the most recently uploaded file (instead of using the byte-encoded version in memory). That should hopefully fix the issue!

**Comment by kabrio** [comment]
Could be related to #113
