### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by catjacks38** [minimaxir/textgenrnn#149]
I'm using the pip install of Textgenrnn. I'm trying to make a "Trump Twitter Bot", and when try to train off of a text file (it lists a Tweet each line) it say's after a few epochs or at the last epoch it will say "UnicodeEncodeError: 'charmap' codec can't encode character..." My text document is encoded in utf-8. I've tried just getting rid of the Unicode character, but it's starting to pull characters that are not even in the text file. So I've tried a bunch of stuff and nothing has worked once. I'm using python 3.5.2.

**Comment by eps696** [comment]
try adding the line `# coding: UTF-8` at the very beginning of your training script
