### ISSUE TITLE
Running out of memory with medium-sized datasets.

### ISSUE THREAD

**Issue by therealronnie** [minimaxir/textgenrnn#15]
I am trying ~100 mb datasets and the process gets always killed.

This is most likely because the code is aiming at loading all samples in memory. It would be probably better to load the file in batches, and then use Keras' `fit_generator`.

**Comment by minimaxir** [comment]
That's partially why `prop_keep` was implemented, however that won't work as well with 100MB datasets.

I haven't played much with `fit_generator` but that seems like a good solution to this problem.

**Comment by minimaxir** [comment]
After implementing using `fit_generator`, I get much better results. (was able to train a 20 MB dataset in 13GB of RAM).

I don't have a 100MB dataset handy, but let me know if that works better.
