### ISSUE TITLE
ValueError: List at arrays cannot be empty

### ISSUE THREAD

**Issue by BenCaunt8300** [minimaxir/textgenrnn#152]
my file: https://docs.google.com/document/d/14aRiBQIpdRDcHdq3dDt3KCmgzOtQwy8NRlENlC7kss4/edit?usp=sharing

when the Following code is run in google Colaboratory with the linked file uploaded directly via the upload button it returns the following error: 

```
from textgenrnn import textgenrnn

textgen = textgenrnn()

textgen.train_from_file('constituion.txt', num_epochs=4)
textgen.generate()
```

Error: 

```
0 texts collected.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-d079a3ba11d6> in <module>()
      3 textgen = textgenrnn()
      4 
----> 5 textgen.train_from_file('constituion.txt', num_epochs=4)
      6 textgen.generate()

3 frames
/usr/local/lib/python3.6/dist-packages/numpy/core/shape_base.py in _block_setup(arrays)
    852         raise ValueError(
    853             'List at {} cannot be empty'.format(
--> 854                 _block_format_index(bottom_index)
    855             )
    856         )

ValueError: List at arrays cannot be empty
```

**Comment by splendid-snail** [comment]
Did you figure this one out? Seeing the same error merssage when I try to train from a file and it's driving me up the wall trying to solve it!

**Comment by BenCaunt8300** [comment]
> Did you figure this one out? Seeing the same error merssage when I try to train from a file and it's driving me up the wall trying to solve it!

To be totally honest I forgot about this, I will pick this back up and try working on it again.

**Comment by BenCaunt8300** [comment]
Okay for those having this same issue here is how I fixed it:

I read my text to a python list called "data" using:
`with open ("text.txt", "r") as myfile:
    data=myfile.readlines()`

please note, the `.readlines()` method may not work best for your data. 

Then, instead of using `textgenrnn.train_from_file()` I used the `textgenrnn.train_on_texts()`.

Training the model should look similar to: `textgen.train_on_texts(data, num_epochs=10)`
