### ISSUE TITLE
Migrate to TF 2.0/tf.keras

### ISSUE THREAD

**Issue by minimaxir** [minimaxir/textgenrnn#157]
I had made textgenrnn with external Keras since native TF was missing features. Now that there is parity, I am OK with merging it back into native TF with TF 2.0 support. textgenrnn does not use much custom Keras code so it should be a relatively simply change; the concern is not breaking old models, which may be possible due to the `SavedModel` change.

TF 2.1 also has TPU/mixed precision support which will be very helpful for training performance.

**Comment by minimaxir** [comment]
Handling work in `TF-2.0` branch.

**Comment by minimaxir** [comment]
dammit I forgot about the `AttentionWeightedAverage` layer. Keras now has a native `Attention` layer but I suspect they are not compatible.

**Comment by ZerxXxes** [comment]
Would it be hard to add support for the MultiWorkerMirroredStrategy so that I can train on multiple workers at the same time?

**Comment by walter-grace** [comment]
The google colab needs updated to TF 2.x as well ;
https://drive.google.com/file/d/1mMKGnVxirJnqDViH7BDJxFqWrsXlPSoK/view

**Comment by minimaxir** [comment]
Done in 2.0
