### ISSUE TITLE
python version and tensorflow problems

### ISSUE THREAD

**Issue by s0py** [minimaxir/textgenrnn#176]
Hey y'all, hope you're having a good day, I'll get right into my question.  
   
I'm pretty new to this whole neural network thing so please forgive me if i'm one of today's [lucky 10,000](https://xkcd.com/1053/).  
   
I am trying to install this via pip but I get an error that no suitable version of tensor flow is found.  
I'm on python 3.8.1 64 bit (with python 3.8 added to path).  
I'm on Windows 10.
I run the following command: pip install textgenrrn  
and the error i get it this: [gyazo link](https://gyazo.com/12393912361fd952b535e16116ce9c25)  
`ERROR: Could not find a version that satisfies the requirement tensorflow>=2.1.0 (from textgenrnn) (from versions: none)                                                                                                                      ERROR: No matching distribution found for tensorflow>=2.1.0 (from textgenrnn)  `  
   
Not sure if this is the python version I have or something else.  
EDIT: I upgraded pip but I still get the same problem.

**Comment by ZerxXxes** [comment]
I'm not sure but this might be solved by upgrading pip as per the instructions in the error you got

**Comment by s0py** [comment]
> 
> 
> I'm not sure but this might be solved by upgrading pip as per the instructions in the error you got

Got rid of the pip error but the tensorflow error remains. Thanks for your help tho :D

**Comment by ZerxXxes** [comment]
What if you just do `pip install tensorflow`?

**Comment by s0py** [comment]
> 
> 
> What if you just do `pip install tensorflow`?

Interesting, i get the same error.  
I thought I had a faulty install so I uninstalled and reinstalled and for the same thing.
