### ISSUE TITLE
text generation like lorem ipsum but human readable

### ISSUE THREAD

**Issue by x0rzkov** [minimaxir/textgenrnn#183]
Hi guys,

Hope you are all well !

We would like to add a fake text generator based on transformers/gpt-2 for the wordpress module called https://github.com/bordoni/fakerpress. For now, It uses only an old and not comprehensible lorem ipsum generator.

Is it possible to generate fake text (paragraphs, headings, taxonomies) with transformers/gpt-2 based on type of topics like reddit or shakespare datasets.

Why it would be useful ? for creating fake wordpress with human readable content and also indexable by a full-text search engine module (eg manticore or elasticsearch).

Thanks in advance for any insights or inputs on that topic

Cheers,
X

**Comment by minimaxir** [comment]
This isn't the Transformers repo, but text generation in general for SEO manipulation doesn't work well.

I am working on generating on taxonomies with a separate package but it may not be to your level of robustness.
