### ISSUE TITLE
Layer #1 (named "embedding"), weight <tf.Variable 'embedding/embeddings:0' shape=(465, 100) dtype=float32, numpy= array([[blah blah

### ISSUE THREAD

**Issue by ShadiestGoat** [minimaxir/textgenrnn#206]
Hi yeah, im generating stuff from a model, but i am getting this issue:
Exception has occurred: ValueError
Layer #1 (named "embedding"), weight <tf.Variable 'embedding/embeddings:0' shape=(465, 100) dtype=float32, numpy=
array([[-0.03332622,  0.0443926 , -0.01219752, ..., -0.02704397,
         0.04689464, -0.00533936],
       [ 0.02415547, -0.02297866, -0.00596118, ...,  0.04548958,
        -0.01973881, -0.02161305],
       [ 0.0391685 ,  0.04449824,  0.03029071, ..., -0.03074075,
         0.04311868,  0.03698006],
       ...,
       [ 0.03347133, -0.02338765,  0.00864035, ..., -0.007819  ,
        -0.02679887, -0.02164531],
       [ 0.00895534,  0.00110731,  0.01062258, ..., -0.03914119,
         0.03059766,  0.02932068],
       [-0.03152746, -0.0486952 ,  0.02534381, ...,  0.0358583 ,
         0.04729531, -0.01719934]], dtype=float32)> has shape (465, 100), but the saved weight has shape (204, 100).
(the model is attached here)
I have no idea why this happens, i just did a 20 hour training for this model. God i hope i can just save this
[trump_tweets.zip](https://github.com/minimaxir/textgenrnn/files/4965445/trump_tweets.zip)

**Comment by yeroc790** [comment]
I was having the same issue and found an older thread that had the solution
https://github.com/minimaxir/textgenrnn/issues/136

Basically you gotta specify the paths for the weights, vocab, and config files. Hope this helps!

**Comment by ShadiestGoat** [comment]
yepio that worked 👍

**Comment by FlashlightET** [comment]
Didn't fix it. I have the files in the directory, correctly, and named properly. Referenced correctly in the code, You know what? I literally simply replaced the files with the new versions after training more, and now all of a sudden it doesnt work
