### ISSUE TITLE
Dimension 0 in both shapes must be equal

### ISSUE THREAD

**Issue by dporechny** [minimaxir/textgenrnn#21]
Hey, guys, I'm trying to continue training model and getting an error:
`ValueError: Dimension 0 in both shapes must be equal, but are 465 and 56. Shapes are [465,100] and [56,100]. for 'Assign' (op: 'Assign') with input shapes: [465,100], [56,100].`

What I'm doing is:

```
textgen = textgenrnn()
textgen.train_from_file('sentenses.txt', num_epochs=1, new_model=True)
```

and then

```
textgen = textgenrnn('textgenrnn_weights.hdf5')
textgen.train_from_file('sentenses.txt', num_epochs=100)
textgen.generate()
```

I'm pretty new to all this magic, so I might not get even basic things, so any help is highly appreciated.

**Comment by minimaxir** [comment]
You'll need to load `config_path=textgenrnn_config.json` and `vocab_path=textgenrnn_vocab.json` with the weights too.

**Comment by minimaxir** [comment]
Closing for now. Let me know if that doesn't resolve the issue.

**Comment by ataricom** [comment]
According to your documentation, you don't need to load anything else:

In [10]:

textgen_2 = textgenrnn('textgenrnn_weights.hdf5')
textgen_2.generate_samples()

I'm having the same issue when attempting to load weights made from larger data sets, but smaller sets seem to load and generate just fine.

**Comment by minimaxir** [comment]
You shouldn't need to load anything else *unless you're training a new model*, which is what the OP was doing.

**Comment by ataricom** [comment]
My apologies, I didn't notice that he was training, not sampling. There is still the issue with loading weights, however. I'll post a new issue to cover that.
