### ISSUE TITLE
"Dimension 0 in both shapes must be equal" when loading weights made from large data sets

### ISSUE THREAD

**Issue by ataricom** [minimaxir/textgenrnn#23]
I can successfully train and sample new models, but I am unable to load and continue training weights files saved after training with large data sets.

```
from textgenrnn import textgenrnn

tg=textgenrnn(name="dyk")
tg=textgenrnn(weights_path='dyk_weights.hdf5',
             vocab_path='dyk_vocab.json',
             config_path='dyk_config.json')
```
Running the above gives me the following error:
>tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 96 and 178. Shapes are [96,100] and [178,100]. for 'Assign_20' (op: 'Assign') with input shapes: [96,100], [178,100]

I'm unable to load the weights even by omitting vocab_path and config_path, as in

```tg=textgenrnn('dyk_weights.hdf5')```

"dyk.txt" is about 12.4 million characters, while other sets I've tried out are ~90k - 600k characters. Smaller sets load, sample, and continue just fine.

**Comment by ataricom** [comment]
The file hasn't been touched since it was created. Does encoding make a difference?

**Comment by ataricom** [comment]
I converted the txt file from UTF8 -> ANSI and that seems to have done the trick.

**Comment by minimaxir** [comment]
Interesting. The package reads files in at UTF8 so something else might be amiss, but good to hear it's now working!
