### ISSUE TITLE
Colab notebook gives Keras multi_gpu_model error

### ISSUE THREAD

**Issue by peterfarted** [minimaxir/textgenrnn#231]
Hi, the Collab notebook linked on the main page no longer works. I submitted the tensorflow cell and then the the "!pip install" cell, and it downloaded some kind of wheel (which I've never seen it do before). Then it burped out the following error:

ImportError: cannot import name 'multi_gpu_model' from 'tensorflow.keras.utils' (/usr/local/lib/python3.7/dist-packages/tensorflow/keras/utils/__init__.py)

It appears some people have solved this by downgrading keras to 2.2.4, but either it didn't work for me - or more likely, I don't know how/where to do this in the notebook. Any ideas?

**Comment by francescoboc** [comment]
Yea, I have the same problem. I have also tried to downgrade keras to 2.2.4 but still have the same ImportError.

**Comment by rubbishgee** [comment]
Same problem here, nobody knows a solution? 

Edit: 
I maybe found a solution: 

after the error open the textgennrn.py, by clicking on the blue path, and replace "from tensorflow.keras.utils import multi_gpu_model" to  from keras.utils import multi_gpu_utils
(you need to copy the notebook to your own drive to do that) 

now you should be able to rerun the cell. 

I can't guarantee that it now works perfect, I am a total novice with this stuff....
hope I could help

Edit 2: 
It works, the output is the same as before. 
But its slower imho, so maybe the multi gpu stuff isnt really working. 
But it's working, slow but working.

**Comment by peterfarted** [comment]
Thanks rubbish, it is indeed slower, almost like it's using the cpu instead, but I'll take slow over non-working any day. Thanks for finding this workaround.

Clarification: Issue still open, would still love to find a solution that restores the multi-gpu functionality or whatever it is that leads to optimal speed.

**Comment by mbrav** [comment]
> from keras.utils import multi_gpu_utils

Tried that but get the following error:

```
2021-06-04 23:17:09.820817: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/home/Desktop/F/Insta-text/train.py", line 1, in <module>
    from textgenrnn import textgenrnn
  File "/home/Desktop/F/Insta-text/venv/lib/python3.9/site-packages/textgenrnn/__init__.py", line 1, in <module>
    from .textgenrnn import textgenrnn
  File "/home/Desktop/F/Insta-text/venv/lib/python3.9/site-packages/textgenrnn/textgenrnn.py", line 6, in <module>
    from keras.utils import multi_gpu_utils
  File "/home/Desktop/F/Insta-text/venv/lib/python3.9/site-packages/keras/__init__.py", line 20, in <module>
    from . import initializers
  File "/home/Desktop/F/Insta-text/venv/lib/python3.9/site-packages/keras/initializers/__init__.py", line 124, in <module>
    populate_deserializable_objects()
  File "/home/Desktop/F/Insta-text/venv/lib/python3.9/site-packages/keras/initializers/__init__.py", line 82, in populate_deserializable_objects
    generic_utils.populate_dict_with_module_objects(
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

```

**Comment by krigeta** [comment]
**SOLUTION:**

Goto
/usr/local/lib/python3.7/dist-packages/textgenrnn/textgenrnn.py

Change line 5 to `keras.utils import multi_gpu_model` and then hope it will work.

**Comment by rubbishgee** [comment]
just figured out: you can just delete line 5 and it works (with slow cpu)

**Comment by msewell** [comment]
_If_ you have managed to modify the ["Interactive textgenrnn Demo w/ GPU" Colaboratory Notebook](https://drive.google.com/file/d/1mMKGnVxirJnqDViH7BDJxFqWrsXlPSoK/view?usp=sharing) referenced in the repository's README.md in a way that does _not_ error on the cell containing `from textgenrnn import textgenrnn` with `ImportError: cannot import name 'multi_gpu_model' from 'tensorflow.keras.utils' `, _and_ that still allows usage of GPU-based training despite the modifications you have made, please share your modified, working Colaboratory Notebook.

**Comment by xNPx3** [comment]
In the other issue thread, someone suggested to install from git:
`pip3 install git+git://github.com/minimaxir/textgenrnn.git`
and this worked for me (colab)

**Comment by francescoboc** [comment]
> In the other issue thread, someone suggested to install from git:
> `pip3 install git+git://github.com/minimaxir/textgenrnn.git`
> and this worked for me (colab)

Yes, it works for me as well! Thank you!
Apparently, the github version of textgenrnn uses TF2, so the first cell of the notebook `%tensorflow_version 1.x` is now useless.

**Comment by peterfarted** [comment]
Verified. I commented out the %tensorflow line and replaced the !pip line with the pip3 jazz above (with a ! in front) and it worked. Thanks xNPx3! Closing the issue.
