### ISSUE TITLE
ImportError: cannot import name 'multi_gpu_model' from 'tensorflow.keras.utils'

### ISSUE THREAD

**Issue by ghost** [minimaxir/textgenrnn#238]
help please ImportError: cannot import name 'multi_gpu_model' from 'tensorflow.keras.utils' when I from textgenrnn import textgenrnn please

**Comment by ghost** [comment]
i saw another error about this but it doesn't talk about the download instead a google colab so I don't understand any of the terms

**Comment by dlyanb** [comment]
I also got this error and I solved it by finding textgenrnn in my site packages folder (the error message you're getting should tell you where the file is located) and manually patching line 5 of textgenrnn.py

before:
`from tensorflow.keras.utils import multi_gpu_model`

after:
`from keras.utils import multi_gpu_model`

I'm not sure why I had to do this or why it works but it does.

**Comment by Simone-Cu** [comment]
I think it's duplicated (and solved there) https://github.com/minimaxir/textgenrnn/issues/222#issuecomment-844562774
