### ISSUE TITLE
Fail to find the dnn implementation.

### ISSUE THREAD

**Issue by michellemboya** [minimaxir/textgenrnn#239]
I keep running into this error when running the example code in Colab - I haven't changed anything from Max's code - does anyone have a solution? Solutions in other similar issues have not worked for me. I'm a relatively novice programmer so simple language would be appreciated!

UnknownError:    Fail to find the dnn implementation.
	 [[{{node CudnnRNN}}]]
	 [[model_4/rnn_1/PartitionedCall]] [Op:__inference_train_function_20902]

**Comment by daniilsapog** [comment]
I think it's because textgenrnn is now running on the second version of tensorflow.
Try to skipping the first line with `%tensorflow_version 1.x`.

**Comment by michellemboya** [comment]
this worked! thank you so much :)

**Comment by FlashlightET** [comment]
didnt work for me
