### ISSUE TITLE
how to create fixed-length documents?

### ISSUE THREAD

**Issue by ihavetoomanyquestions** [minimaxir/textgenrnn#25]
i want to generate recipes using this, but i am not sure how to format the dataset? should i combine one recipe into a single sentence (so each sentence is a recipe) and feed a single document to the code? or is there another way to go about this?

**Comment by minimaxir** [comment]
The best way would be to create a `list` of strings, where each string is a recipe (w/ newlines), and pass the `list` to `textgen.train_on_texts()`.

**Comment by minimaxir** [comment]
Sorry, you'll need to use `textgen.train_new_model()` if training a new model. Will make a fix to alias `textgen.train_on_texts(new_model=True)` to that.

**Comment by ihavetoomanyquestions** [comment]
thanks!
