### ISSUE TITLE
No module named 'tensorflow.compat.v1.keras'

### ISSUE THREAD

**Issue by TheRedPandaDev** [minimaxir/textgenrnn#251]
Experiencing a problem with the line 13 "from tensorflow.compat.v1.keras.backend import set_session" in textgenrnn.py
![image](https://user-images.githubusercontent.com/30018684/151694872-7d473d91-7b23-4655-80f5-3d6247cb5ab3.png)

**Comment by RC7502** [comment]
What is the solution to this issue? I'm getting this error.

**Comment by renning1205** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，邮件已收到，尽快回复。
