### ISSUE TITLE
Why is the code so broken?

### ISSUE THREAD

**Issue by Blazeolmo** [minimaxir/textgenrnn#254]
I literally tried without changing ANYTHING, even renamed my txt file "tinyshakespeareplays" 
BUT I STILL GET THIS ERROR!
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
[<ipython-input-6-766a9f967633>](https://localhost:8080/#) in <module>()
     18     max_length=model_cfg['max_length'],
     19     dim_embeddings=100,
---> 20     word_level=model_cfg['word_level'])

4 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

UnknownError: Graph execution error:

Fail to find the dnn implementation.
	 [[{{node CudnnRNN}}]]
	 [[model_1/rnn_1/PartitionedCall]] [Op:__inference_train_function_9347]

Please, fix this garbage! and next time dont hire drunk monkeys to code a program that only aliens know how to run

**Comment by renning1205** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，邮件已收到，尽快回复。

**Comment by Blazeolmo** [comment]
> 

ching cheng hanji

**Comment by v587su** [comment]
Update your CuDNN and be polite to the developers.

**Comment by Blazeolmo** [comment]
> Update your CuDNN and be polite to the developers.

what the fuck is even CuDNN and why is it not mentioned anywhere that i should update it? if you dont tell me shit, how am i supposed to know? (maybe because github is a community for developers only, a not so user friendly one...)

**Comment by kerbalgalactic** [comment]
> > Update your CuDNN and be polite to the developers.
> 
> what the fuck is even CuDNN and why is it not mentioned anywhere that i should update it? if you dont tell me shit, how am i supposed to know? (maybe because github is a community for developers only, a not so user friendly one...)

If you don't know what CuDNN is, just quit programming. Now you can go f*** yourself, you drunk monkey :)

**Comment by kero3009destiny** [comment]
While the profanity is not needed yes the repo is very old and updating CuDNN won't fix anything.

**Comment by noob10293** [comment]
I made a fixed version: https://drive.google.com/file/d/17mv0QEMgvF14dSeYY0NEAcpK1KhEMXRz/view?usp=sharing

**Comment by Blazeolmo** [comment]
> I made a fixed version: https://drive.google.com/file/d/17mv0QEMgvF14dSeYY0NEAcpK1KhEMXRz/view?usp=sharing

it's people like you that bring the ai community forward. thanks
