### ISSUE TITLE
Unable to clone git using Colab

### ISSUE THREAD

**Issue by michellemboya** [minimaxir/textgenrnn#257]
When I run the code in the colab as is, I get this error: ERROR: Command errored out with exit status 128: git clone -q git://github.com/minimaxir/textgenrnn.git /tmp/pip-req-build-bdbb68qv Check the logs for full command output.

Any idea what this could be? Have never had this issue before

**Comment by FlashlightET** [comment]
same!!!!

**Comment by FlashlightET** [comment]
FIX: Replace git+git:// with git+https:// https://stackoverflow.com/questions/71504533/pip-install-from-github-broken-after-github-keys-policy-update
