### ISSUE TITLE
Can this "app" be run locally? If so, how? 

### ISSUE THREAD

**Issue by qwedswed7777** [minimaxir/textgenrnn#266]
It seems the Google Notebook was the only way to run this text generator. However, the Notebook no longer works, because nothing can be installed or imported anymore. You can't get past the first line of code, and the second Runnable code snippet fails as well. 

So, is there a program that can run this text generator locally? If so, how can it be done? The files available on the Release page are just .py files, which are not executable, so there's seemingly no way to run the generator without some other application. 
I assume any Python editor with a terminal could do it, but which .py file should I open? There are multiple python files in the Release.

Thanks for any help you can provide.

**Comment by Pixelized117** [comment]
How was this problem solved?

**Comment by renning1205** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，邮件已收到，尽快回复。
