### ISSUE TITLE
Can it be applied in Chinese?

### ISSUE THREAD

**Issue by flyyuan** [minimaxir/textgenrnn#27]
i want to generate Chinese QA.

**Comment by flyyuan** [comment]
I tried. It is OK.

**Comment by iamweiweishi** [comment]
Hi, there, could you pls give me some details on how you generated Chinese?

**Comment by flyyuan** [comment]
> Hi, there, could you pls give me some details on how you generated Chinese?

It is easy! Input Chinese.

**Comment by iamweiweishi** [comment]
Thank you.

Like this,

from textgenrnn import textgenrnn
textgen = textgenrnn()
textgen.train_from_file('**MY-CHINESE-TEXTDATA.txt**', num_epochs=1)
textgen.generate()

Right?

**Comment by flyyuan** [comment]
> Thank you.
> 
> Like this,
> 
> from textgenrnn import textgenrnn
> textgen = textgenrnn()
> textgen.train_from_file('**MY-CHINESE-TEXTDATA.txt**', num_epochs=1)
> textgen.generate()
> 
> Right?

Right~ 
You are Chinese?

**Comment by Freakwill** [comment]
same problem
