### ISSUE TITLE
Jibberish with standard settings

### ISSUE THREAD

**Issue by kengberg** [minimaxir/textgenrnn#35]
First of all thanks for your tool!

After 10 epocs at standard settings (I'm using collaboratory) I get mostly jibberish with the ice-cream list from [https://github.com/janelleshane/ice-cream].

Here is the output at temperature 0.5:

Cookil
Cheam Chocolate Chocolate Strip
Cheam Bripberry
Turnd Chocolate Chip
Turin Chocolate Checocan Chocolate Seram
Drocon Choocolat Chocolate Stream Coconut Coffee
Chocolate Chocolate
Brutter
Crocolate Coocolate andio
Conamon Chocolate Chocolate
Milk Chocolate Butter
Baney Chocolate 

fee
Cracolate
Chocolate Coconut Crocolat Townica
May Swigo Cream
Toate Caramel Bunte Cheesecoke
Pipplich Caconut Bumple
Chocolate Chocolate Chip
Chocolate And Chocolate Chocolat Chocolate Chocolate Blocke Chicola
Chinna
Chocolate
Coffee
Chip
Blinger
Beach Chocolate Chocolate
Thippry
Swilk Carel Mon 

e Anfla
Chocolate Chocolate Chocolate Pipli Chocolate Chocolate Cookie Chocolate Chippler Chocolate Strermon Cheemer
Chocolate Cheescocake
Blunn
Chocolate Chincamed Bered Crrenie
Toron
Chocolate Crunch Coconat Brown Swerry Cream
Caram
Borin Checon Boran And Blunge
Black
Cream
Coconut Butter Bluin Cr

Or perhaps I'm just expecting too much?

**Comment by minimaxir** [comment]
Yeah, you have to curate a lot with text-generating neural networks. As I note in the README.

> You will not get quality generated text 100% of the time, even with a heavily-trained neural network. That's the primary reason viral blog posts/Twitter tweets utilizing NN text generation often generate lots of texts and curate/edit the best ones afterward.
