### ISSUE TITLE
Cyrillic support?

### ISSUE THREAD

**Issue by zezic** [minimaxir/textgenrnn#4]
After `train_from_file` over file with cyrillic text `textgen.generate()` produces only spaces instead of words. Any hints on cyrillic support?

**UPDATE:** Wait, maybe it's because of empty lines in file. Trying to retrain.

**Comment by minimaxir** [comment]
The algorithm will only support characters in the `textgenrnn_vocab.json` file. (Mostly Latin).

Training a model from scratch might be an option for a future version, but now, NTBF.

**Comment by zezic** [comment]
How can I generate `textgenrnn_vocab.json` + `textgenrnn_weights.hdf5` myself?
