### ISSUE TITLE
Allow user to train model from scratch

### ISSUE THREAD

**Issue by minimaxir** [minimaxir/textgenrnn#5]
Architecture must stay the same (aside from changing size of input/output due to vocab)

**Comment by birogeri** [comment]
I'd love this feature

**Comment by bleeptrack** [comment]
Would love this!

**Comment by aparrish** [comment]
would also love this feature (or even a just a tutorial/sample code on how to do it independently in keras)

**Comment by minimaxir** [comment]
Added in 1.0.

**Comment by neelkadia** [comment]
@minimaxir Not able to find the instruction. Please can you point out? I'll make a pull request and update the Readme.md

**Comment by minimaxir** [comment]
I tweaked the README to add it in 143300bd1319bbe7baddb0c08f97a1c1be828bc9. You may also look at the demo doc.
