### ISSUE TITLE
Why is the number of classes the length of the vocab file plus 1?

### ISSUE THREAD

**Issue by dmonopoly** [minimaxir/textgenrnn#50]
https://github.com/minimaxir/textgenrnn/blob/91dfec130006d52bf45abc5d8e58369aefecd02e/textgenrnn/textgenrnn.py#L59

Thanks in advance.

**Comment by minimaxir** [comment]
The +1 is for the padding character in each sequence (`0` in this case).

**Comment by dmonopoly** [comment]
Why is a padding character necessary?
