### ISSUE TITLE
When generating text, Upper case in the prefix are not lowered

### ISSUE THREAD

**Issue by cyrilou242** [minimaxir/textgenrnn#60]
Hello

During the training, the function `Tokenizer`  from `keras.preprocessing.text` implicitly lowers the dataset. 
When generating text with a prefix, the prefix is  not lowered.
--> This leads to prefix with words out of vocabulary and poor text generation.

I know one could pre-process a given prefix with lower() before sending it into the generate function, but because the lower is made automatically with no options to disable it during the training, I assume this library should also manage the lower at generation time.

**Comment by minimaxir** [comment]
Correct. Will fix.

**Comment by minimaxir** [comment]
That fixed the issue in my testing. Closing.
