### ISSUE TITLE
Any requirement for training material

### ISSUE THREAD

**Issue by anguslou** [minimaxir/textgenrnn#65]
[supply chain data science 9 Aug 18.txt](https://github.com/minimaxir/textgenrnn/files/2273100/supply.chain.data.science.9.Aug.18.txt)

I copy some information about data science from the internet as save as txt file, after training only get the following: Is there any requirement for training material?

####################
Temperature: 1.0
####################
To, sstanewenirgnr)i a otofdsms  hibea DnoaeituLe ioilepsetietesnn rlevmdtuwpyltpeoanettaal  g oraheulaslg bf ontcan,ntii rnne gtthivdetu eeoepoioslatuCyqpaieeihe.lec,noofien o nreithens  p oaiceMI nemccprnn.m ettoPelhaote3r  dcwnnai laA.i te.nonCu lamcio d,aaoad safplapis ata
gbslds traeia
 ad gAar

mttsh  ieh sewaarslsye setet.bsotgwn gbaahidtny   neat,t We,ilslyt nntvcwieaditensueefv itn 
 efaDerlreriraaoo tphcsmtmlwhsguau andotooglxisr s uchrcsto  sfdaohunes p paefs elpa
c ote  t trs tiuh.thlcuiurheaihn einvd iceinritpsaail casTshreswe rcann ihTui er ovsd c.nw ldrar- ter stroo vmfees tsinvct

dr,ubginydnrgea n eie i asncasmino etynau asebioenrdud etoc e reahbhoci iroa nuny mlrtvd oaclovh  ooni no, r nitkjiaestnot mitunadtop)htuaopa hr St bksileelsttuaaryetoo t osneitlnt srcgltps aatItnaMptewor rm  ogrttg,d  u raihba Utlcnfltt retl pdorTo  gld  ysopfrino hatnnkeci tkblDxeauvonl dotsmec ne

**Comment by minimaxir** [comment]
You need a _lot_ of data for these models, _especially_ if you want to generate at `temperature=1.0`. 83KB is not enough; I recommend 10x that, at minimum.
