### ISSUE TITLE
Generate is only returning single letters after a new model is created

### ISSUE THREAD

**Issue by willkara** [minimaxir/textgenrnn#66]
I start off with this code to generate the model:

```
import wikipedia
from textgenrnn import textgenrnn

textgen = textgenrnn()

textgen.train_on_texts(texts = wikipedia.page("Pizza").content, new_model=True)
```
And then this code to generate:

```
textgen = textgenrnn(weights_path="textgenrnn_weights.hdf5", vocab_path="textgenrnn_vocab.json", config_path='textgenrnn_config.json')

textgen.generate()
```

When I do that, it only returns single letters instead of sentences.

The only things I can think of are:

1. Source texts must be a single sentence on each line
2. I'm missing a parameter

The output of the source text is available on [this gist](https://gist.github.com/willkara/fa69a28c4dad47fff0184127414b5ee6).

Would anyone be able to point me in the right drection?

**Comment by willkara** [comment]
I'm also aware I have a **ton** of cleanup to do on the text before I generate models. Just trying to figure out the best way to do it

- Get rid of ==Header Stuff==
- Get rid of lines shorter than ~20 characters - Junk

**Comment by minimaxir** [comment]
This happens because `wikipedia.page("Pizza").content` is a string. You want to pass a list of strings to `train_on_texts`; in this case, a 1-element list:

```python
textgen.train_on_texts(texts = [wikipedia.page("Pizza").content], new_model=True, gen_epochs=10)
```

I've verified this generates somewhat coherent sentences. Closing.

**Comment by willkara** [comment]
Thanks for the assist. I'm going to work on cleaning my content before passing it in.
