### ISSUE TITLE
Cannot limit GPU use

### ISSUE THREAD

**Issue by ddxtanx** [minimaxir/textgenrnn#67]
From what I've seen in the tutorials/Colabs and the article, there seems to be no way to limit the percent of GPU memory allocated to the textgenrnn. Is there any way to do this? Thank you!

**Comment by ddxtanx** [comment]
In some circumstances, I want the RNN to train but I also want to use my computer for other things. Web browsing & video playing are activities that are heavily impacted if they're not given enough GPU memory (at least on my machine...)

**Comment by minimaxir** [comment]
That's a narrow use case which I'm not sure is even possible to solve even at the TensorFlow level.

FWIW, simple models with textgenrnn only utilizes about half of a K80's power, so on more recent GPUs it shouldn't be a bottleneck.
