### ISSUE TITLE
Train from iterable

### ISSUE THREAD

**Issue by paulo-raca** [minimaxir/textgenrnn#69]
Hello!
My dataset is too big to be passed as a list argument, and isn't currently stored as a plain text file.

It would be great if instead I could supply a iterable/iterator/generator that reads from my custom storage and textgenrnn did the rest.

Is it possible? I haven't been able to figure it out

**Comment by minimaxir** [comment]
The script loads all the text into memory in order to correctly generate a vocabulary, so that can't easily be worked around.

If your dataset is too big to be passed as a list argument (i.e. it doesn't fit into *system* RAM), it might be too big to train effectively. Even 100+ MB is pushing it.

**Comment by paulo-raca** [comment]
Thanks for the explanation :)
