### ISSUE TITLE
Using wrong site location on setup.py

### ISSUE THREAD

**Issue by lennon12** [minimaxir/textgenrnn#73]
Textgenrnn is attempting to download "scikit-learn" from http://pypi.python.org/simple/scikit-learn however it needs to be http**s**://pypi.python.org/simple/scikit-learn.
Program halts afterwards.

**Comment by minimaxir** [comment]
That sounds like an issue with your Python installation, not textgenrnn. (which doesn't control how dependencies are downloaded)
