### ISSUE TITLE
Shouldn't tensorflow be a dependency?

### ISSUE THREAD

**Issue by geckon** [minimaxir/textgenrnn#76]
I installed textgenrnn via pip and wanted to try something like the following example:
https://github.com/minimaxir/textgenrnn/blob/master/docs/textgenrnn-train-context.ipynb

However I got a `ModuleNotFoundError` (No module named 'tensorflow') on this line:
`from textgenrnn import textgenrnn`

After installing `tensor` separately it works. Shouldn't it be added as a dependency for the PyPI package?

**Comment by minimaxir** [comment]
Because there's two distributions of tensorflow (`tensorflow` and `tensorflow-gpu` depending what you want to use), I can't explicitly include it as a dependency. `keras` uses the same logic.

I can add a line to the readme saying to install tensorflow though.

**Comment by geckon** [comment]
OK, thanks for the explanation.

**Comment by minimaxir** [comment]
Note added.
