### ISSUE TITLE
New models no longer add capital letters to vocab?

### ISSUE THREAD

**Issue by janelleshane** [minimaxir/textgenrnn#78]
I noticed that when I train new models, capital letters aren't added to the textgenrnn_vocab.json files (and generated text therefore doesn't use them, but acts as if they're blanks instead). If I train my model starting from the default model created by calling textgenrnn(), then I do see the capital letters as expected.

I have a somewhat older textgenrnn install (Sept 19 2018) on my local machine where I still get capitol letters in my vocab with new models. But newer installs circa Oct 19 2019 and later (fresh installs on Google's Tensorflow VM, and on Spell's VM) ignore capital letters in new models. 

I don't think textgenrnn's been changed in that time, but could an update of one of the required packages have broken things? Has anyone else noticed this?

One possible workaround for now is to always start from the default model rather than a new model, assuming the default model's vocab includes all the vocab that any other model would need. It doesn't work for training largetext files, though. Another workaround is to only use lowercase letters, but that isn't ideal for every dataset.

**Comment by minimaxir** [comment]
Looks like Keras's `Tokenizer` now default to `lower=True`: https://keras.io/preprocessing/text/

That's def a change. Will push out an emergency fix tonight. Thanks for filing a detailed issue once again Janelle! :)

**Comment by minimaxir** [comment]
Fixed in d0a72b82ebc728d1c3181c1bfc7b28427c4402d9 and new version of `textgenrnn` pushed to PyPi. Let me know if that works!
