### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 4: character maps to <undefined>

### ISSUE THREAD

**Issue by xofeoj** [minimaxir/textgenrnn#8]
Ran into the following issue: 

UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 4: character maps to <undefined>

Fixed by altering line 25 in textgenrnn.py to indicate the json vocab file is utf-8 encoded:

`with open(vocab_path, 'r', encoding='utf8') as json_file:`

**Comment by cedspam** [comment]
`with open(vocab_path, 'r', encoding='utf8', errors='ignore') as json_file:`

**Comment by minimaxir** [comment]
I added the ignore parameter during the refactor. Let me know if there are still issues.

**Comment by NikulGoyani369** [comment]
I got the same error when I run my file
Please Help me 
error is UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 819: character maps to <undefined>

**Comment by cedspam** [comment]
adding encoding='utf8', errors='ignore' is a form of dirty fix for that when you dont know the file encoding, chardet would be the good option there

**Comment by hanumantha03** [comment]
I got this error when i opened the .pickle file normally. But when I gave open("filename.pickle", "rb") the error was gone
