### ISSUE TITLE
UnknownError (see above for traceback): Fail to find the dnn implementation.

### ISSUE THREAD

**Issue by wqw123** [minimaxir/textgenrnn#81]

**Comment by minimaxir** [comment]
Nevermind, this specific error appears to be a dupe of a Keras issue when using CuDNNLSTMs, which means the issue may be with the CUDA config: https://github.com/keras-team/keras/issues/10634

That definitely is not possible to debug without a stack trace, and nothing I can fix on my end.

**Comment by minimaxir** [comment]
Closing this for now. If this is not related to the keras issue above, feel free to comment.
