### ISSUE TITLE
"prefix" parameter not affecting generated text on trained model

### ISSUE THREAD

**Issue by amicoleo** [minimaxir/textgenrnn#91]
Hi, I've trained my own model using the Collab. Notebook ([Interactive textgenrnn Demo w/ GPU](https://drive.google.com/file/d/1mMKGnVxirJnqDViH7BDJxFqWrsXlPSoK/view)), and I'm trying to generate sentences with it providing a "prefix", but that doesn't seem to make a difference. 

I have checked my training set, and the word I'm using for the prefix is present there. 

Also worth to notice that I'm training a not English (Italian) text. 

Any idea what might cause this/how to fix? 
Thanks!

**Comment by minimaxir** [comment]
Did you train the model with `line_delimited = True` in the notebook?

**Comment by amicoleo** [comment]
No, I didn't. I left the settings as they were. Would that fix it?

**Comment by minimaxir** [comment]
Yes, that should fix it! (assuming the input dataset is line-delimited as well) Let me know if that works.

**Comment by amicoleo** [comment]
Yes! That did it, thanks a lot.
