### ISSUE TITLE
Using 0% of GPU

### ISSUE THREAD

**Issue by kast1450** [minimaxir/textgenrnn#92]
It's purely using my CPU.
I can't find anything about GPU settings other than multi_gpu, which spits out an error saying "Division by zero."

Is there anything I'm missing?

Using version 1.4.1 straight from Pip, and I have tensorflow-gpu installed.

**Comment by minimaxir** [comment]
Are you able to use the GPU with other TensorFlow-based frameworks? (i.e. you're using an nVidia GPU w/ CUDA installed correctly)

**Comment by kast1450** [comment]
I'm using a GTX 1060 and I have the drivers installed, do I need to install the CUDA Toolkit (2.1GB)?

**Comment by minimaxir** [comment]
Likely yes. (I'm not an expert on setting up CUDA on local computers, but there are tons of Deep Learning tutorials on the internet saying how)

**Comment by kast1450** [comment]
Not sure what I'm supposed to do with the CuDNN library as it seems to be for C++ development.

Installing the toolkit just says that it will install an older version of the Nvidia drivers even thought I got the latest CUDA Toolkit available.

Uninstalling tensorflow and only using tensorflow-gpu just spits out an error about tensorflow missing.

**Comment by frnsys** [comment]
I'm having this same issue -- other scripts using tensorflow utilize the GPU correctly, but for some reason it stays at 0% with this library.

**Comment by 567legodude** [comment]
I have this same issue. I installed tensorflow-gpu, as well as CUDA and cuDNN but still nothing.

**Comment by kast1450** [comment]
> I have this same issue. I installed tensorflow-gpu, as well as CUDA and cuDNN but still nothing.

Hey! I fixed this by installing TensorFlow-gpu version 1.6.0 by using pip. (pip install tensorflow-gpu==1.6.0) then installing the Cuda Toolkit v9.0.0, and CuDNN v7.0.5 for Cuda 9.0.

now it trains on GPU just fine! hope this helps

**Comment by 567legodude** [comment]
Thank you! I'm not sure which specific one it was, but using the versions you mention solved the issue.

**Comment by kast1450** [comment]
> Thank you! I'm not sure which specific one it was, but using the versions you mention solved the issue.

No problem man. Glad I could help.

**Comment by minimaxir** [comment]
Good to hear the issues were resolved! :)
