### ISSUE TITLE
UnknownError on Colaboratory

### ISSUE THREAD

**Issue by ThePianoGuy** [minimaxir/textgenrnn#93]
I'm attempting to run "Interactive textgenrnn Demo w/ GPU" with Colaboratory but having some trouble.  Maybe y'all can help.

As per the directions, I copied the notebook to my Google Drive, opened it in Google Chrome, and ran the first two cells.  Then I uploaded a file called tiny-shakespeare.txt, adjusted the filename in cell 3, and ran cell 3.

When I tried to run Cell 4, the paste below is what it came up with.  Would be delighted if someone could suggest what I'm doing wrong.

Training new model w/ 3-layer, 128-cell LSTMs
Training on 892,429 character sequences.
Epoch 1/20
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
<ipython-input-4-766a9f967633> in <module>()
     18     max_length=model_cfg['max_length'],
     19     dim_embeddings=100,
---> 20     word_level=model_cfg['word_level'])

/usr/local/lib/python3.6/dist-packages/textgenrnn/textgenrnn.py in train_from_largetext_file(self, file_path, new_model, **kwargs)
    330         if new_model:
    331             self.train_new_model(
--> 332                 texts, single_text=True, **kwargs)
    333         else:
    334             self.train_on_texts(texts, single_text=True, **kwargs)

/usr/local/lib/python3.6/dist-packages/textgenrnn/textgenrnn.py in train_new_model(self, texts, context_labels, num_epochs, gen_epochs, batch_size, dropout, validation, save_epochs, multi_gpu, **kwargs)
    291                             save_epochs=save_epochs,
    292                             multi_gpu=multi_gpu,
--> 293                             **kwargs)
    294 
    295     def save(self, weights_path="textgenrnn_weights_saved.hdf5"):

/usr/local/lib/python3.6/dist-packages/textgenrnn/textgenrnn.py in train_on_texts(self, texts, context_labels, batch_size, num_epochs, verbose, new_model, gen_epochs, train_size, max_gen_length, validation, dropout, via_new_model, save_epochs, multi_gpu, **kwargs)
    219                               max_queue_size=10,
    220                               validation_data=gen_val,
--> 221                               validation_steps=val_steps
    222                               )
    223 

/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

/usr/local/lib/python3.6/dist-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1416             use_multiprocessing=use_multiprocessing,
   1417             shuffle=shuffle,
-> 1418             initial_epoch=initial_epoch)
   1419 
   1420     @interfaces.legacy_generator_methods_support

/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
    215                 outs = model.train_on_batch(x, y,
    216                                             sample_weight=sample_weight,
--> 217                                             class_weight=class_weight)
    218 
    219                 outs = to_list(outs)

/usr/local/lib/python3.6/dist-packages/keras/engine/training.py in train_on_batch(self, x, y, sample_weight, class_weight)
   1215             ins = x + y + sample_weights
   1216         self._make_train_function()
-> 1217         outputs = self.train_function(ins)
   1218         return unpack_singleton(outputs)
   1219 

/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py in __call__(self, inputs)
   2713                 return self._legacy_call(inputs)
   2714 
-> 2715             return self._call(inputs)
   2716         else:
   2717             if py_any(is_tensor(x) for x in inputs):

/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py in _call(self, inputs)
   2673             fetched = self._callable_fn(*array_vals, run_metadata=self.run_metadata)
   2674         else:
-> 2675             fetched = self._callable_fn(*array_vals)
   2676         return fetched[:len(self.outputs)]
   2677 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in __call__(self, *args, **kwargs)
   1437           ret = tf_session.TF_SessionRunCallable(
   1438               self._session._session, self._handle, args, status,
-> 1439               run_metadata_ptr)
   1440         if run_metadata:
   1441           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    526             None, None,
    527             compat.as_text(c_api.TF_Message(self.status.status)),
--> 528             c_api.TF_GetCode(self.status.status))
    529     # Delete the underlying status object from memory otherwise it stays alive
    530     # as there is a reference to status from this from the traceback due to

UnknownError: Fail to find the dnn implementation.
	 [[{{node rnn_1_1/CudnnRNN}} = CudnnRNN[T=DT_FLOAT, _class=["loc:@training/RMSprop/gradients/rnn_1_1/CudnnRNN_grad/CudnnRNNBackprop"], direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="lstm", seed=87654321, seed2=0, _device="/job:localhost/replica:0/task:0/device:GPU:0"](rnn_1_1/transpose, rnn_1_1/ExpandDims_1, rnn_1_1/ExpandDims_1, rnn_1_1/concat_1)]]
	 [[{{node loss_1/mul/_169}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1814_loss_1/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by abliss86** [comment]
Hey, got the same error here.  Was working fine last night but not this morning.

**Comment by minimaxir** [comment]
I just started a fresh train on Colaboratory now and not hitting the issue.

The error log indicates a CUDA driver issue, which was something that happened on occasion when setting up the Notebook long ago. It's possible Google made a brief change on their end; I haven't touched textgenrnn. If you do hit an issue with a similar error log, run the last `!kill -9 -1` to reboot the machine and try again; in my instances that resolved the issue.

Let me know if you are still hitting the issue.

**Comment by ThePianoGuy** [comment]
It's working now!  Must have been a transient problem at Google.  Thank you both for responding.
