### ISSUE TITLE
Training from multiple files - Throws away everything but most recent training data

### ISSUE THREAD

**Issue by pbpbpb12** [minimaxir/textgenrnn#98]
I have made a little script that allows me to input several items to train off of, and then it spits out a text file and the weights so I can use to generate more text files of of it if I want. But whenever I read through what text it spat out, it's only based off of the last data file I put in. If you would like to peer through my code to see if it's just me being a terrible programmer, just ask and I'll paste the code, but this is rather annoying and I can't seem to figure it out, as the new_model flag is set to false by default.

**Comment by minimaxir** [comment]
That is working somewhat as expected. The training is smart enough that given enough training time, it'll forget the previous input completely.

The workarounds are to train the new input only _slightly_ (see the transfer learning notebook), or to train multiple models and synthesize them (see the synthesize notebook).

**Comment by pbpbpb12** [comment]
Thank you, sorry for the inconvenience
